config/routes.rb
AngelHack::Application.routes.draw do
  
  namespace :admin do
    resources :categories
  end

  get "testing/index"

  namespace :api do
    match "pinlog(/:user_id)" => "pinlog#index", :via => :get
    match "pinlog/create" => "pinlog#create", :via => :post
    
    match "upload" => "upload#create", :via => :post
    
    match "user/create" => "user#create", :via => :post 
    match "user/update" => "user#update", :via => :post
    match "user/destroy" => "user#destroy", :via => :delete
    match "user/show" => "user#show", :via => :get
    match "user(/:bb_pin)" => "user#index", :via => :get
    
    match "marketplace(/:friend_level)(/:user_id)" => "marketplace#index", :via => :get
    match "items/create" => "marketplace#create", :via => :post
  end

  root :to => 'testing#index'

end

app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
  attr_accessible :category_name
  
  validates :category_name, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category_name
  
  has_many :items
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Admin::Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_categories }
    end
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
    @admin_category = Admin::Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_category }
    end
  end

  # GET /admin/categories/new
  # GET /admin/categories/new.json
  def new
    @admin_category = Admin::Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_category }
    end
  end

  # GET /admin/categories/1/edit
  def edit
    @admin_category = Admin::Category.find(params[:id])
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Admin::Category.new(params[:admin_category])

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to @admin_category, notice: 'Category was successfully created.' }
        format.json { render json: @admin_category, status: :created, location: @admin_category }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/categories/1
  # PUT /admin/categories/1.json
  def update
    @admin_category = Admin::Category.find(params[:id])

    respond_to do |format|
      if @admin_category.update_attributes(params[:admin_category])
        format.html { redirect_to @admin_category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category = Admin::Category.find(params[:id])
    @admin_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for(@admin_category) do |f| %>
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @admin_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_name %><br />
    <%= f.text_field :category_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing admin_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_category %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Listing admin_categories</h1>

<table>
  <tr>
    <th>Category name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_categories.each do |admin_category| %>
  <tr>
    <td><%= admin_category.category_name %></td>
    <td><%= link_to 'Show', admin_category %></td>
    <td><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
    <td><%= link_to 'Destroy', admin_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New admin_category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category name:</b>
  <%= @admin_category.category_name %>
</p>


<%= link_to 'Edit', edit_admin_category_path(@admin_category) %> |
<%= link_to 'Back', admin_categories_path %>